apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
    component: backend
    alias: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-backend
    component: backend
