name: Release - Production

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build & Push Production Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=main-
            type=raw,value=latest

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update production Helm values
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "Updating production environment with tag: main-${SHORT_SHA}"
          
          # Update Helm values for production environment
          sed -i "s|tag:.*|tag: main-${SHORT_SHA}|g" helm/app/values/prod.yaml
          
      - name: Commit production values changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add helm/app/values/prod.yaml
          
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          git commit -m "chore(prod): update image tag to main-${SHORT_SHA} [skip ci]" || echo "No changes"
          git push

  release-complete:
    name: Production Release Complete
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Summary
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "✅ Production Release Complete"
          echo ""
          echo "✅ Production images built: main-${SHORT_SHA}"
          echo "✅ Production manifest updated"
          echo "✅ ArgoCD will sync automatically"
