apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-corp-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lebrick07/acme-corp-api.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: acme-corp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
