apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techstart-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lebrick07/techstart-webapp.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: techstart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
