apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: widgetco-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lebrick07/widgetco-api.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: widgetco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
